# Generated by Django 5.1.7 on 2025-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('n_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=5000)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20)),
                ('cliente', models.CharField(max_length=5000)),
                ('tecnico', models.CharField(max_length=5000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
